version: "3.8"

volumes:
  redis_data:

services:
#  migrations:
#    we don't need special migrations service because we use SQLITE
#    ...

  cache:
    container_name: redis
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --include /usr/local/etc/redis/redis.conf

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cache
    ports:
      - "12000:8000"
    restart: always
#    command: ./start.sh
